sonar.projectKey=comercios-microservices
sonar.organization=brandon-isla

# Analiza ambos microservicios como un solo proyecto (monorepo).
sonar.sources=comercios-service/src/main,notificaciones-service/src/main
sonar.tests=comercios-service/src/test,notificaciones-service/src/test
sonar.java.binaries=comercios-service/target/classes,notificaciones-service/build/classes/java/main
sonar.java.source=21
