spring:
  application:
    name: notificaciones-service
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5434/notificaciones}
    username: ${DB_USER:comercios}
    password: ${DB_PASSWORD:comercios}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:comercios}
    password: ${RABBITMQ_PASSWORD:comercios}

server:
  port: ${PORT:8081}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
